# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-24 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
